version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi_app
    command: sh -c 'PYTHONPATH=/usr/src/app uvicorn backend.app.main:app --host=0.0.0.0 --port 8080'
    restart: always
    working_dir: /app/backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

  frontend:
    build: ./frontend
    container_name: react_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://backend:8080"
    command: ["yarn", "start"]

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"